# Generated by Django 4.0.3 on 2022-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waterfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя')),
                ('image', models.ImageField(upload_to='waterfalls_images')),
                ('description', models.TextField(max_length=60, verbose_name='описание')),
                ('place', models.TextField(default='место не указанно', max_length=60, verbose_name='место')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='')),
                ('S', models.PositiveIntegerField(default=0, verbose_name='')),
                ('water_consumption', models.PositiveIntegerField(default=0, verbose_name='')),
                ('Altitude_above_sea_level', models.PositiveIntegerField(default=0, verbose_name='')),
                ('Energy_joules', models.PositiveIntegerField(default=0, verbose_name='')),
                ('cordinats', models.FloatField(default=0, verbose_name='cordinats')),
            ],
        ),
    ]
