# Generated by Django 4.0.3 on 2022-07-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_waterfall_cordinats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', models.BinaryField(blank=True, db_column='photo', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='waterfall',
            name='image',
        ),
    ]
