# Generated by Django 4.0.3 on 2022-07-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_blobimg_remove_waterfall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobimg',
            name='_data',
            field=models.ImageField(blank=True, db_column='photo', null=True, upload_to=''),
        ),
    ]
