# Generated by Django 4.0.3 on 2022-07-16 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_blobimg__data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blobimg',
            name='_data',
        ),
        migrations.AddField(
            model_name='blobimg',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='waterfalls_images'),
            preserve_default=False,
        ),
    ]
