# Generated by Django 4.0.3 on 2022-07-16 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_blobimg__data_blobimg_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlobImg',
        ),
        migrations.AddField(
            model_name='waterfall',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='waterfalls_images'),
            preserve_default=False,
        ),
    ]
