# Generated by Django 4.0.3 on 2022-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_blobimg_waterfall_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterfall',
            old_name='S',
            new_name='S_catchment',
        ),
        migrations.AddField(
            model_name='waterfall',
            name='S_mirror',
            field=models.PositiveIntegerField(default=0, verbose_name=''),
        ),
    ]
