# Generated by Django 4.0.3 on 2022-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_s_waterfall_s_catchment_waterfall_s_mirror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
    ]
