# Generated by Django 4.0.3 on 2022-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_waterfall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='Altitude_above_sea_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота над ур. моря'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='Energy_joules',
            field=models.PositiveIntegerField(default=0, verbose_name='Энергия в джоулях'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='S_catchment',
            field=models.PositiveIntegerField(default=0, verbose_name='Площадь водосбора'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='S_mirror',
            field=models.PositiveIntegerField(default=0, verbose_name='Площадь зеркала в кв. м'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='cordinats',
            field=models.FloatField(verbose_name='кординаты'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='image',
            field=models.ImageField(upload_to='waterfalls_images', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='water_consumption',
            field=models.PositiveIntegerField(default=0, verbose_name='Расход воды в куб. м'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='ширина'),
        ),
    ]
