# Generated by Django 4.0.3 on 2022-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_waterfall_altitude_above_sea_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='cordinats',
            field=models.FloatField(default='не указанно', verbose_name='кординаты'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='description',
            field=models.TextField(default='не указанно', max_length=60, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='image',
            field=models.ImageField(default='waterfalls_images/', upload_to='waterfalls_images', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='name',
            field=models.CharField(default='не указанно', max_length=128, verbose_name='Имя'),
        ),
    ]
