# Generated by Django 4.0.3 on 2022-09-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_waterfall_cordinats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterfall_District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(default='не указанно', max_length=128, verbose_name='Имя')),
                ('District_description', models.TextField(default='не указанно', max_length=60, verbose_name='описание')),
            ],
        ),
        migrations.AddField(
            model_name='waterfall',
            name='District_id',
            field=models.PositiveIntegerField(default=0, verbose_name='айди района'),
        ),
        migrations.AddField(
            model_name='waterfall',
            name='type',
            field=models.TextField(default='-', max_length=60, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='cordinats',
            field=models.TextField(default='-', verbose_name='кординаты'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='description',
            field=models.TextField(default='-', max_length=60, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='image',
            field=models.ImageField(blank=True, default='-', upload_to='waterfalls_images', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='name',
            field=models.CharField(default='-', max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='place',
            field=models.TextField(default='-', max_length=60, verbose_name='место'),
        ),
    ]
