# Generated by Django 4.0.3 on 2022-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_administrative_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='Administrative_District_id',
            field=models.PositiveIntegerField(default=1, verbose_name='айди административного района'),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='District_id',
            field=models.PositiveIntegerField(default=1, verbose_name='айди района'),
        ),
    ]
