# Generated by Django 4.0.3 on 2022-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_waterfall_administrative_district_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='description',
            field=models.TextField(default='-', max_length=1024, verbose_name='описание'),
        ),
    ]
