# Generated by Django 4.0.3 on 2022-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_waterfall_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(default=' ', max_length=128, verbose_name='название')),
                ('text', models.TextField(default=' ', max_length=8192, verbose_name='текст')),
            ],
        ),
    ]
